name: Release Exesh

on:
  pull_request:
    branches: [master]
    types: [closed]

permissions:
  contents: read

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release-component.yml
    with:
      component: exesh
      build: true
      build_dir: Backend/Exesh/ansible/build
      deploy_dir: Backend/Exesh/ansible/deploy
      vault: true
    secrets: inherit
