name: Release Nginx

on:
  pull_request:
    branches: [master]
    types: [closed]

permissions:
  contents: read

jobs:
  release:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/release-component.yml
    with:
      component: nginx
      build: false
      deploy_dir: Backend/nginx/ansible/deploy
      vault: false
    secrets: inherit
